/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as NewRouteImport } from './routes/new'
import { Route as InbjudningarRouteImport } from './routes/inbjudningar'
import { Route as FavoriterRouteImport } from './routes/favoriter'
import { Route as DriftRouteImport } from './routes/drift'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIdRouteImport } from './routes/docs.$id'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InbjudningarRoute = InbjudningarRouteImport.update({
  id: '/inbjudningar',
  path: '/inbjudningar',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoriterRoute = FavoriterRouteImport.update({
  id: '/favoriter',
  path: '/favoriter',
  getParentRoute: () => rootRouteImport,
} as any)
const DriftRoute = DriftRouteImport.update({
  id: '/drift',
  path: '/drift',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIdRoute = DocsIdRouteImport.update({
  id: '/docs/$id',
  path: '/docs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drift': typeof DriftRoute
  '/favoriter': typeof FavoriterRoute
  '/inbjudningar': typeof InbjudningarRoute
  '/new': typeof NewRoute
  '/support': typeof SupportRoute
  '/docs/$id': typeof DocsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drift': typeof DriftRoute
  '/favoriter': typeof FavoriterRoute
  '/inbjudningar': typeof InbjudningarRoute
  '/new': typeof NewRoute
  '/support': typeof SupportRoute
  '/docs/$id': typeof DocsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drift': typeof DriftRoute
  '/favoriter': typeof FavoriterRoute
  '/inbjudningar': typeof InbjudningarRoute
  '/new': typeof NewRoute
  '/support': typeof SupportRoute
  '/docs/$id': typeof DocsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drift'
    | '/favoriter'
    | '/inbjudningar'
    | '/new'
    | '/support'
    | '/docs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drift'
    | '/favoriter'
    | '/inbjudningar'
    | '/new'
    | '/support'
    | '/docs/$id'
  id:
    | '__root__'
    | '/'
    | '/drift'
    | '/favoriter'
    | '/inbjudningar'
    | '/new'
    | '/support'
    | '/docs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriftRoute: typeof DriftRoute
  FavoriterRoute: typeof FavoriterRoute
  InbjudningarRoute: typeof InbjudningarRoute
  NewRoute: typeof NewRoute
  SupportRoute: typeof SupportRoute
  DocsIdRoute: typeof DocsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbjudningar': {
      id: '/inbjudningar'
      path: '/inbjudningar'
      fullPath: '/inbjudningar'
      preLoaderRoute: typeof InbjudningarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoriter': {
      id: '/favoriter'
      path: '/favoriter'
      fullPath: '/favoriter'
      preLoaderRoute: typeof FavoriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drift': {
      id: '/drift'
      path: '/drift'
      fullPath: '/drift'
      preLoaderRoute: typeof DriftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$id': {
      id: '/docs/$id'
      path: '/docs/$id'
      fullPath: '/docs/$id'
      preLoaderRoute: typeof DocsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriftRoute: DriftRoute,
  FavoriterRoute: FavoriterRoute,
  InbjudningarRoute: InbjudningarRoute,
  NewRoute: NewRoute,
  SupportRoute: SupportRoute,
  DocsIdRoute: DocsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
